### ISSUE TITLE
TS definitions support?

### ISSUE THREAD

**Issue by ali-habibzadeh** [Enteee/plantuml-parser#23]
**Is your feature request related to a problem? Please describe.**
It's almost a universal expectation for modules to have types so they can be used in a TS application.

**Describe the solution you'd like**
If you are coding in TS, ship with `declaration: true` but you can also add it separately to https://github.com/DefinitelyTyped.

**Describe alternatives you've considered**
I will have a go at creating something and will let you know when I have something.

**Additional context**
No.

**Comment by Enteee** [comment]
Thank you for submitting this @ali-habibzadeh.

The project does currently not expose any types/interfaces. But I can see the advantage of the formatters returning a strongly typed result.

>  I will have a go at creating something and will let you know when I have something.

That would be much appreciated! :+1: 
I will therefore leave this open for now and wait for more feedback and maybe input from others.

**Comment by geopic** [comment]
Are you still working on this @ali-habibzadeh? I'd be happy to take over if you're ok with that.

**Comment by Enteee** [comment]
@geopic thank you for your interest in this issue. Since I have not heard anything, I do think @ali-habibzadeh has abandoned this. 

@ali-habibzadeh : Please correct me if I am wrong.
@geopic : I would really appreciate your contribution.

**Comment by geopic** [comment]
I'll get started on it within a few days then, unless @ali-habibzadeh objects.

**Comment by Enteee** [comment]
Great, don't hesitate to ask questions if you have any. I'll be monitoring GitHub closely.

**Comment by geopic** [comment]
Hey @Enteee I have some questions about the options object for `.parse`. Are the possible options the ones listed [here](https://pegjs.org/documentation#generating-a-parser-javascript-api) *and* listed [here](https://github.com/okaxaki/pegjs-backtrace#options)? What data types are expected from the `allowedStartRules` and `plugins` properties?

**Comment by Enteee** [comment]
> Are the possible options the ones listed here and listed here?

It's both.  The option object will be forwarded [to the generated parser](https://github.com/Enteee/plantuml-parser/blob/3f7a7cfc6569ca9bf17b51a95c4bdba22ee494f0/src/index.js#L42). And also [to the `Tracer` ](https://github.com/Enteee/plantuml-parser/blob/3f7a7cfc6569ca9bf17b51a95c4bdba22ee494f0/src/index.js#L21). I found that the two options don't intersect and both silently ignore unknown options, therefore I merged the two in one object. I could actually really improve the documentation around that.

> What data types are expected from the allowedStartRules and plugins properties?

Those are both options for the parser generator, not the parser itself. The supported options are documented [here](https://pegjs.org/documentation#using-the-parser). But I would actually not expose `startRule` to the user, since that will almost always break the parser.

Which means what I would expose and document in the type is the following (mostly tracer options)
* [`verbose`](https://github.com/Enteee/plantuml-parser/blob/3f7a7cfc6569ca9bf17b51a95c4bdba22ee494f0/src/index.js#L20)
* `hiddenPaths`
* `useColor`
* `showTrace`
* `maxSourceLines`
* `maxPathLength`
* `matchesNode`

**Comment by Enteee** [comment]
I am not quite sure which `return` statement you mean, but the return statement of `parse` exposed by the module is [here](https://github.com/Enteee/plantuml-parser/blob/3f7a7cfc6569ca9bf17b51a95c4bdba22ee494f0/src/index.js#L42) which really just forwards the returned parsed tree according to the [parsing expression grammar](https://github.com/Enteee/plantuml-parser/blob/master/src/plantuml.pegjs). The actual parser is [here](https://github.com/Enteee/plantuml-parser/blob/master/src/plantuml.js), but since that's all auto generated you don't want to look at that.

For your purpose it's probably best if you have a look at:
* [the parsing expression grammar](https://github.com/Enteee/plantuml-parser/blob/master/src/plantuml.pegjs)
* [all the different types](https://github.com/Enteee/plantuml-parser/tree/master/src)
* [the formatters](https://github.com/Enteee/plantuml-parser/tree/master/src/formatters) (Note: The default formatter just does a `return JSON.stringify(..)`. No magic there)

**Comment by geopic** [comment]
@Enteee Thanks for the help and taking time to link to some resources.

**Comment by Enteee** [comment]
Implemented with #33
